### ISSUE TITLE
`context` is initially undefined since v1.9.0

### ISSUE THREAD

**Issue by dan-lee** [contrawork/graphql-helix#90] opened 2021-11-03 20:45 UTC
Since v1.9.0 the `context` in a resolver seems to be initially undefined.

This leads to errors like

> Cannot read properties of undefined (reading 'session')

Here's a repro: https://stackblitz.com/edit/node-ysprk8

I've just taken [the context example from `graphql-helix`](https://github.com/contrawork/graphql-helix/tree/master/examples/context).
When you switch the versions in the stackblitz from `v1.9.0` to `v1.8.4` in `package.json` it will work again.

**Comment by hayes** [comment] 2021-11-03 23:32
this is related to execute removing support for positional args.

Args for execute were converted to be an object, but they key for context should have been updated to be `contextValue` but is being passed as `context` 

https://github.com/contrawork/graphql-helix/commit/c8750f308aad58bf9e1b9f5d97f5ea3a55d43c3a#diff-6c8aa63d319597d6d7fff26fda262c760963d5a73d99ad303c0da528bbd376a5R140

Technically this was also a breaking change since any provided context function is now called with completely different arguments.

I think it would probably also make sense to align formatResult with this new API so both are called with `contextValue` to keep things consistent (this is also a breaking change)

**Comment by hayes** [comment] 2021-11-03 23:38
Happy to submit an PR if you want, just need to know how to resolve this (which combination of the following fixes makes sense). 

1. Just call execute with the `contextValue`
2. Update types for custom execute function to accept same arg shape as default execute
3. Map old execute format to new execute format so API does not change
4. Update formatPayload to also accept context as `contextValue`

**Comment by dotansimha** [comment] 2021-11-04 07:42
@ardatan can you please check this?

**Comment by ilijaNL** [comment] 2021-11-04 09:06
Confirmed this. It also breaks usage with getEveloped (https://github.com/dotansimha/envelop)

**Comment by n1ru4l** [comment] 2021-11-04 10:09
Fix is being worked on in https://github.com/contrawork/graphql-helix/pull/91

**Comment by mcrawshaw** [comment] 2021-11-04 12:03
Confirmed as resolved in 0.9.1.

**Comment by bigint** [comment] 2021-11-04 12:18
Working perfect now thanks!

**Comment by n1ru4l** [comment] 2021-11-04 12:40
🎉

**Closed by n1ru4l** 2021-11-04 12:40 UTC
